global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "food-tinder-app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["food-tinder-app:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
