#name: Build & Push Docker Image
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    name: TinderFood - Build & Push
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Log in to Docker registry
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#      - name: Build and push Docker image
#        run: make docker-build
#
#      - name: Deploy to ${{ inputs.environment }}
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          port: 22
#          script: |
#            cd infra
#            ./deploy.sh
#